name: Build python

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: build
        run: pip wheel -v --no-deps -w wheelhouse .

      - name: Keep wheel files
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl

      - name: Keep version
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: PYPI_VERSION

  release:
    runs-on: ubuntu-latest
    needs: build-python

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: wheelhouse
          path: wheelhouse
      
      - uses: actions/download-artifact@v3
        with:
          name: version
          path: .

      - name: List wheels
        run: |
          ls ./wheelhouse/*.whl -al
          cat PYPI_VERSION

